language: go

go:
  - 1.4.1

install:
  - go get -t -v ./...
  - go install github.com/onsi/ginkgo/ginkgo
  - curl -L https://github.com/coreos/etcd/releases/download/v2.0.2/etcd-v2.0.2-linux-amd64.tar.gz | tar zxf - -C /tmp
  - mv /tmp/etcd-v2.0.2-linux-amd64/etcd $HOME/gopath/bin
  - go get github.com/apcera/gnatsd
  - go get github.com/cloudfoundry-incubator/auction/simulation/repnode

before_script:
  - export PATH=$HOME/gopath/bin:$PATH

script: ginkgo -r -race -failOnPending -randomizeAllSpecs
